Fix undefined reference to static constant member
It turns out that you have to DEFINE static const members apart from declaring
them in a class!! (but only if you pass them by reference or get their address).